# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy


In [1]:
import numpy as np

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [2]:
# Crear un arreglo de ceros de longitud 12
arreglo_de_ceros = np.zeros(12)
print(arreglo_de_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
# Crear un arreglo de longitud 10 con ceros en todas las posiciones
arreglo = np.zeros(10)

# Asignar un valor de 10 en la posición número 5 (índice 4)
arreglo[4] = 10

print(arreglo)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [4]:
# Crear un arreglo con los números del 10 al 49
arreglo = np.arange(10, 50)

print(arreglo)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
# Crear un arreglo 2D de forma (3, 3) con los números del 0 al 8
arreglo_2d = np.arange(9).reshape(3, 3)

print(arreglo_2d)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
# Crear un arreglo de números aleatorios de longitud 100
arreglo_aleatorio = np.random.rand(100)

# Calcular la media y la varianza
media = np.mean(arreglo_aleatorio)
varianza = np.var(arreglo_aleatorio)

print("Arreglo aleatorio:", arreglo_aleatorio)
print("Media:", media)
print("Varianza:", varianza)

Arreglo aleatorio: [0.59336944 0.02508555 0.3931666  0.40290621 0.71482483 0.08322257
 0.16611485 0.17903856 0.31437777 0.8270255  0.17022076 0.90337286
 0.88971431 0.21417876 0.58116879 0.15449359 0.90755637 0.34260717
 0.15333376 0.33691912 0.70450466 0.77289267 0.7806222  0.79656555
 0.95427245 0.32151766 0.8087028  0.8674189  0.12003134 0.69439529
 0.30975187 0.5187028  0.77817925 0.04723171 0.6310991  0.79735261
 0.6611023  0.09238516 0.7287219  0.2425902  0.36969214 0.74469813
 0.32277772 0.69887683 0.64538006 0.64553793 0.01125423 0.85338925
 0.49070631 0.40275044 0.47017422 0.64048445 0.32355266 0.98699887
 0.29336123 0.50254838 0.68822066 0.66279102 0.38350695 0.55694152
 0.47056503 0.2650849  0.94449583 0.65733879 0.54558895 0.31578386
 0.19379183 0.64591917 0.28336223 0.00587184 0.1154103  0.81871269
 0.55996152 0.56571937 0.25020142 0.67637273 0.65048882 0.09603853
 0.50580559 0.97759726 0.31871924 0.86987952 0.61387973 0.0752459
 0.08417445 0.71509706 0.89344031 0.23460551

In [7]:
# Crear un arreglo de ejemplo
arreglo = np.array([1, 2, 3, 4, 5])

# Calcular la media usando np.sum
media = np.sum(arreglo) / len(arreglo)

print("Arreglo:", arreglo)
print("Media:", media)

Arreglo: [1 2 3 4 5]
Media: 3.0


In [8]:
# Crear un arreglo de ejemplo
arreglo = np.array([1, 2, 3, 4, 5])

# Calcular la media con np.mean
media = np.mean(arreglo)

# Calcular la varianza con np.sum y np.mean
varianza = np.sum((arreglo - media) ** 2) / len(arreglo)

print("Arreglo:", arreglo)
print("Media:", media)
print("Varianza:", varianza)

Arreglo: [1 2 3 4 5]
Media: 3.0
Varianza: 2.0


In [9]:

# Crear un arreglo de números aleatorios utilizando np.random.randn
arreglo_aleatorio = np.random.randn(10)

print("Arreglo aleatorio:", arreglo_aleatorio)

Arreglo aleatorio: [ 0.87529792  0.66289023 -0.1951956   0.77221251 -0.30783058 -0.00595419
 -1.15831938 -0.64101477 -1.16912845  1.34081712]
